### PR TITLE
Attempt to enable target display mode upon initial connect

### PR DESCRIPTION
**Pull request by SoneeJohn**
#23
https://github.com/duanefields/VirtualKVM/pull/22

### CODE REVIEW

**Comment by duanefields** [comment]
I not longer have a way to run this code, is it up to date and ready to go?

**Comment by SoneeJohn** [comment]
@duanefields Yeah. I tested it today.

**Comment by reitermarkus** [comment]
@SoneeJohn, this broke my DisplayPort support.

**Comment by SoneeJohn** [comment]
@reitermarkus terribly sorry. I will compare my changes to yours in regards to DisplayPort support.

**Comment by reitermarkus** [comment]
No worries, I already have it working again. Will create a PR soon.

**Pull request merged**
