### PR TITLE
Add macOS Sierra compatibility

### PR DESCRIPTION
**Pull request by alvaromurillo**

### CODE REVIEW

**Comment by duanefields** [comment]
I no longer have a mac that supports Target Display Mode so I have to trust you.

**Comment by xenaton63** [comment]
Hi guys (excuse me for my english).
I really really don't know anything about coding but i'm looking for virtualKVM to work with Sierra. Is there a way to download a build version of this update ?

Thanks you :-)

**Comment by duanefields** [comment]
Do you have an updated build you can send me?

**Comment by alvaromurillo** [comment]
Yes, here you have the release https://github.com/alvaromurillo/VirtualKVM/releases

**Pull request merged**
